"""Description des changements

Revision ID: 320eb7e485b3
Revises: df063f7a5db6
Create Date: 2025-09-11 16:57:24.827634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '320eb7e485b3'
down_revision: Union[str, Sequence[str], None] = 'df063f7a5db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('recieved_from', sa.String(), nullable=True))
    op.add_column('calls', sa.Column('actions_to_be_taken', sa.String(), nullable=True))
    op.alter_column('calls', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('calls', 'updated_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calls', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('calls', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('calls', 'actions_to_be_taken')
    op.drop_column('calls', 'recieved_from')
    # ### end Alembic commands ###
