"""Ajout colonne action_to_be_taken_by à calls

Revision ID: 5095dc4633dd
Revises: 320eb7e485b3
Create Date: 2025-09-12 10:07:42.863425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5095dc4633dd'
down_revision: Union[str, Sequence[str], None] = '320eb7e485b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('action_to_be_taken_by', sa.String(), nullable=True))
    op.drop_column('calls', 'action_to_be_taken')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('action_to_be_taken', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('calls', 'action_to_be_taken_by')
    # ### end Alembic commands ###
