"""Ajout entités appels et référentiels

Revision ID: df063f7a5db6
Revises: 2046def341c7
Create Date: 2025-09-10 13:13:50.226664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df063f7a5db6'
down_revision: Union[str, Sequence[str], None] = '2046def341c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_type_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_index(op.f('ix_call_type_queries_id'), 'call_type_queries', ['id'], unique=True)
    op.create_table('method_of_reply_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_index(op.f('ix_method_of_reply_options_id'), 'method_of_reply_options', ['id'], unique=True)
    op.create_table('response_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_index(op.f('ix_response_status_id'), 'response_status', ['id'], unique=True)
    op.create_table('calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('contact_number', sa.String(), nullable=False),
    sa.Column('type_of_query_id', sa.UUID(), nullable=False),
    sa.Column('reason_of_call', sa.String(), nullable=False),
    sa.Column('answered_by', sa.String(), nullable=False),
    sa.Column('replied_to_id', sa.UUID(), nullable=False),
    sa.Column('replied_method_id', sa.UUID(), nullable=False),
    sa.Column('replied_by', sa.String(), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('action_to_be_taken', sa.String(), nullable=True),
    sa.Column('action_taken', sa.String(), nullable=True),
    sa.Column('other_comments', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('closed', 'pending', 'open', name='callstatus'), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['replied_method_id'], ['method_of_reply_options.id'], ),
    sa.ForeignKeyConstraint(['replied_to_id'], ['response_status.id'], ),
    sa.ForeignKeyConstraint(['type_of_query_id'], ['call_type_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_id'), 'calls', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calls_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_response_status_id'), table_name='response_status')
    op.drop_table('response_status')
    op.drop_index(op.f('ix_method_of_reply_options_id'), table_name='method_of_reply_options')
    op.drop_table('method_of_reply_options')
    op.drop_index(op.f('ix_call_type_queries_id'), table_name='call_type_queries')
    op.drop_table('call_type_queries')
    # ### end Alembic commands ###
